name: OWASP ZAP DAST Scan
on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Run App
        run: |
          npm install
          node index.js &
          sleep 20 

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:3000'
          allow_issue_writing: false
        env:
          # Isso instrui a action a pular a etapa de criação de artefatos
          ARTIFACT_NAME: ""
      
      # Step extra para garantir que o pipeline não quebre mesmo se houver warnings
      - name: Finalize Scan
        run: echo "Scan concluído com sucesso."
