name: OWASP ZAP DAST Scan
on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Run App
        run: |
          npm install
          node index.js &
          sleep 20 

      - name: ZAP Scan (Sem Artefatos)
        run: |
          # Rodamos o ZAP via Docker diretamente, sem tentar salvar artefatos (usando /dev/null)
          docker run --network=host -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t http://localhost:3000
