name: OWASP ZAP DAST Scan
on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Run App
        run: |
          npm install
          node index.js &
          # Aumentamos o sleep para garantir que o express subiu na porta 3000
          sleep 20 

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:3000'
          allow_issue_writing: false
          # Ao deixar o artifact_name vazio, desativamos a tentativa de upload 
          # que estava causando o erro Bad Request (400)
          artifact_name: ""
